### ISSUE TITLE
Could not find a version that satisfies the requirement cookielib

### ISSUE THREAD

**Issue by kker4m** [alicangnll/BingGPT-Python#1]
Cookielib kutuphanesinin Python 3 ile kalkmasindan dolayi ilgili import şu şekilde değiştirilebilir;

```python
    try:
        import cookielib
    except:
        import http.cookiejar
```

**Comment by alicangnll** [comment]
Evet, yapılabilir. Lütfen dosyayı değiştirip bize pull request açın. Onaylayalım. Adınız projede geçsin.
