### ISSUE TITLE
Meet the max conversation limit

### ISSUE THREAD

**Issue by thd2020** [alicangnll/BingGPT-Python#3]
I guess the program is talking to Sydney... Because somehow after several sentences there's an error "veri unbounded", and as I looking into the code, I found veri not being assigned a value. The truth is code never runs to the line where the variable veri is assigned, and for a weird reason it just bypass that and call it later on...
So I found this in the response of Sydney:
'{"type":1,"target":"update","arguments":[{"requestId":"df0607f6-50ef-48bb-b0b8-5c87aaba4c5f","throttling":{"maxNumUserMessagesInConversation":20,"numUserMessagesInConversation":1}}]}'
The code is looking for a non-existent json property "messages" from it which cause the failure. I'm still not getting through why "messages" has gone.

**Comment by alicangnll** [comment]
Can you share the text you sent to BingGPT with me? Can you also take a screenshot of this error?

**Comment by thd2020** [comment]
Sorry to lose the logs. But it seems to crash in the `block` here:
`          
               while not final:

                try:
                    objects = str(await wsscon.recv()).split("")
                except:
                    final = True
                    try:
                        return "Answer : " + veri
                    except:
                        return "An error occured! Please try again!"
                for obj in objects:
                    if obj is None or obj == "":
                        continue
                    response = json.loads(obj)
                    try:
                        if response["type"] == 1:
                            if response["arguments"][0]["messages"][0]["text"]:`
The last line wants to get the first value of "messages" but there's no "messages".

**Comment by alicangnll** [comment]
I am started to research. I will back you as soon.

**Comment by alicangnll** [comment]
Hello, we are researched. So i think that's fixed. Can you check it ?
`pip install --upgrade bingpython`

**Comment by alicangnll** [comment]
I could not reach any comment from you. So, i am closing that issue.
